### ISSUE TITLE
CLIEngine has been deprecated

### ISSUE THREAD

**Issue by ricardogobbosouza** [webpack-contrib/eslint-webpack-plugin#10]
Use new ESLint class
https://eslint.org/docs/user-guide/migrating-to-7.0.0#deprecate-cliengine

**Comment by LKummer** [comment]
Hello, I would like to contribute the migration.

I gathered most changes to the API that affect the plugin:

- ESLint constructor option handling has changed.
  - `options` has changed and is incompatible with `CLIEngine` options.
  - `options` is validated to not contain extra properties.
- Linting method is now asynchronous.
- Formatter objects have changed.
  - It is now an object with a `format()` method.
  - Formatter loading is now asynchronous.
  - Formatter loading method is no longer static.
- Results type has changed.

Most of the work seems pretty straight forward.

I believe it will be best to only support the new API because the options have changed. I am afraid it will be confusing to users that the options will break on update from ESLint 6 to 7.

Is this the approach you have in mind?

**Comment by ricardogobbosouza** [comment]
Hi @LKummer 
I had thought of this refactoring, and drop support ESLINT 6
A PR would be welcome :smile:

**Comment by LKummer** [comment]
Sounds great @ricardogobbosouza.

I have made significant progress already, you can expect a pull request very soon.
