### ISSUE TITLE
Add new option `flatConfigFile`

### ISSUE THREAD

**Issue by ricardogobbosouza** [webpack-contrib/eslint-webpack-plugin#239]
Waiting #238 
Simplify the use of flat config

```js
// before
const ESLintPlugin = require('eslint-webpack-plugin');

module.exports = {
  // ...
  plugins: [new ESLintPlugin({
    configType: 'flat',
    eslintPath: 'eslint/use-at-your-own-risk',
    overrideConfigFile: 'flat-config.js',
  })],
  // ...
};
```

```js
// after
const ESLintPlugin = require('eslint-webpack-plugin');

module.exports = {
  // ...
  plugins: [new ESLintPlugin({
    flatConfigFile: 'flat-config.js',
  })],
  // ...
};
```

1. Create a `flatConfigFile` option that will define:

- The `eslintPath` as `eslint/use-at-your-own-risk`
- The `configType` as `flat`
- The `overrideConfigFile` as `flatConfigFile`

2. Automatically define `flatConfigFile` if there is an `eslint.config.js` file in the project root
3. Add a section in the readme about `flatConfigFile`

**Comment by onigoetz** [comment]
Hi @ricardogobbosouza

I have the impression that the addition of this option will become a problem once ESLint 9 is released

My current understanding, as per these blog posts:

- https://eslint.org/blog/2023/11/whats-coming-in-eslint-9.0.0/
- https://eslint.org/blog/2023/10/flat-config-rollout-plans/

> The ESLint class will now be equivalent to the FlatESLint class in v8.x. With the exception of a few options, this should mostly be a transparent change.

So that means that the import that's done right now will suddenly handle flatConfig instead of eslintrc-style config

So maybe there is something to do with imports to auto-detect ESLint's version or imports to differentiate which one we have loaded? I expect this part of the logic to become more complicated once ESLint 9 is released

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack-contrib/eslint-webpack-plugin/releases/tag/v4.1.0
