### ISSUE TITLE
Non-blocking linting option

### ISSUE THREAD

**Issue by elisherer** [webpack-contrib/eslint-webpack-plugin#33]
- Operating System: N/R
- Node Version: N/R
- NPM Version: N/R
- webpack Version: 4/5
- eslint-webpack-plugin Version: Latest

### Feature Proposal

I suggest to add a boolean option `nonBlocking` (default `false`).
If turned on, after each code change (while "watching") the linting process will be forked to not interfere with the build process.
(Maybe can tap on the last part of the build process, but still be on another thread)
linting warnings/errors will be shown on console. Not sure it can be shown on the browser console because webpack might not know something happened (maybe someone here knows better).

### Feature Use Case
Probably a development only feature:
- The code compilation isn't really affected by lint errors/warnings (usually we use `failOnWarning: false, failOnError: false) . (If there are syntax errors, those will be caught by the transpiler anyway).
- During development, we usually use `emitWarning: true` so we don't expect the build to fail anyway.
- To boost performance of incremental code changes deferring the linting process will release the hot module replacement (or fast refresh) to see the changes in the browser while still showing lint warnings/errors in the dev server console.

WDYT?

**Comment by vegerot** [comment]
I'm currently using `eslint-loader` through `vue-cli-plugin-eslint`, and I think I have a similar question.

When I set `lintOnSave: true`, my time it takes for `npm run serve` to complete quadruples!  And the time it takes to recompile for a HMR is 5x longer :( .  However, this is not the case for the TypeScript service.  For TypeScript, _after_ the devServer finishes compiling and begins serving the page, devServer begins the TypeScript type checking service.  Meaning that the type checking does not slow down the server at all, since it is done asynchronously.  I was looking into switching from `eslint-loader` to `eslint-webpack-plugin`, and one of the main upgrades I was looking for was the ability to lint my codebase in the same way the typechecking service does.

From the sound of this issue, it seems that this is not a feature.  Is such a thing on the roadmap?

Right now in `eslint-loader`, the time it takes to recompile for HMR is unbearable

**Comment by jsg2021** [comment]
It's currently not blocking. With or without threads turned on.

**Comment by elisherer** [comment]
@jsg2021 , after upgrading to the latest (2.4.1) I still see a considerable amount of delay when using the plugin (with or without threads and lintDirtyModulesOnly) vs not using the plugin at all.

**Comment by decademoon** [comment]
@jsg2021 Are you sure? For me, webpack dev server blocks updates and hot reloads until the linting completes after a watched file has changed. Ideally during development the linting should happen in the background without blocking the webpack build. IIRC there's a typescript loader that works like this.

**Comment by jsg2021** [comment]
Sorry, I was responding with the definition of classical "blocking"... and it is non-blocking in that sense... execution continues on the main thread while the linter runs in parallel.  Webpack is waiting on all async parts to complete the report. Which is the blocking you mean.

**Comment by l0gicgate** [comment]
I'm curious is there a reason why the `eslint-loader` did not experience this issue versus the plugin does? Are those changes related to Webpack?

**Comment by jsg2021** [comment]
@decademoon as of 2.5.0 it is fully blocking. Turn on threads and rollback to 2.4.x...

**Comment by stylemistake** [comment]
Can confirm, 2.4 is much faster with threads on.

**Comment by ricardogobbosouza** [comment]
Performance was corrected in [v2.5.4](https://github.com/webpack-contrib/eslint-webpack-plugin/releases/tag/v2.5.4)

**Comment by ricardogobbosouza** [comment]
@elisherer 
Use [`threads`](https://github.com/webpack-contrib/eslint-webpack-plugin#threads) option
